filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/test.log

# WORKING: Using Elasticsearch output (NOT tcp!)
output.elasticsearch:
  hosts: ["104.255.9.187:5044"]
  protocol: "http"
  path: "/"
  index: ""
  bulk_max_size: 1
  username: ""
  password: ""
  ssl.enabled: false
  max_retries: 0
  timeout: 30

logging.level: error
logging.to_files: false
path.data: /var/lib/filebeat
path.logs: /var/log/filebeat
