filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/test.log

# Forward logs to central Fluent Bit instance via HTTP
output.http:
  hosts: ["${CORE_VPS}:5044"]
  ssl.enabled: false
  max_retries: 3
  timeout: 30
  headers:
    Content-Type: application/json

logging.level: error
logging.to_files: false
path.data: /var/lib/filebeat
path.logs: /var/log/filebeat
